export const CROPS = [
  { name: "apple", plantingCount: 48 },
  { name: "beet", plantingCount: 44 },
  { name: "blueberry", plantingCount: 36 },
  { name: "bok choi", plantingCount: 99 },
  { name: "carrot", plantingCount: 22 },
  { name: "corn", plantingCount: 42 },
  // {name: "grapes", plantingCount: 64},
  // {name: "kale", plantingCount: 118},
  // {name: "leeks", plantingCount: 61},
  // {name: "lettuce", plantingCount: 96},
  // {name: "mizuna", plantingCount: 10},
  // {name: "mustard greens", plantingCount: 30},
  // {name: "oats", plantingCount: 234},
  // {name: "peppers", plantingCount: 167},
  // {name: "potato", plantingCount: 450},
  // {name: "spinach", plantingCount: 60},
  // {name: "butternut squash ", plantingCount: 9},
  // {name: "swiss chard", plantingCount: 96},
  // {name: "tomato", plantingCount: 66},
  // {name: "wheat", plantingCount: 187},
  // {name: "zucchini", plantingCount: 259},
  // {name: "all crops", plantingCount: 2459},
];

export const COLORS = [
  "Beige",
  "Brown",
  "Green",
  "Orange",
  "Red",
  "Purple",
  "Brownpurple",
  "Brownred",
  "Yellow",
  "Orangered",
];

export const CROP_VARIETY = [
  "Austrian Crescent",
  "Bonita",
  "Carola",
  "Laratte",
  "Loowit",
  "Phureja-- Andean",
  "Satina",
  "Adirondack Red",
  "Amarosa",
  "Bannock",
  "Caribe",
  "Carola",
  "Cheiftain",
  "Chioggia Guardsmark",
  "Dark Red Norland",
  "Ditta",
  "Elba",
  "Fingerling",
  "French Fingerling",
  "German Butterball",
  "Huckleberry",
  "Jester",
];

export const CLIMATE_REGION = [
  "Central",
  "East North Central",
  "Northeast",
  "Northwest",
  "Other",
  "South",
  "Southeast",
  "Southwest",
  "West",
  "West North Central",
];

export const SAMPLE_SOURCE = [
  "Farm",
  "Farm Market",
  "Farm Retail",
  "Garden",
  "Research Plots",
  "Store",
];

export const FARM_PRACTICES = [
  "Sheet Mulching",
  "None",
  "Covercrops",
  "Organic",
  "Regenerative",
  "Transitioning",
  "Biodynamic",
  "Biological",
  "Nospray",
  "Certified Organic",
  "Irrigation",
];

export const AMENDMENTS = [
  "Mulch",
  "Lime",
  "None",
  "Synth Fertilizer",
  "Organic Amendment",
];

export const LAND_PREPARATION = [
  "None",
  "Tillage",
  "Solarization",
  "Broadforking",
  "Sheet Mulching",
];

export const GROUPS = [
  "ANEI",
  "Bay Area Urban Farmers Association",
  "BeneficialBIO",
  "Bionutrient Institute",
  "BOTL Farm",
  "Carbofarm",
  "CCRP Soils Cross Cutting",
  "CEE",
  "CEPAGRO",
  "CFDN",
  "Cool Farm Tool",
  "corn growers association",
  "CRARS RAD-Lab, Chico State",
  "Demo",
  "farmOS",
  "Flavor",
  "General Mills Regen Ag",
  "GOSH",
  "Grupo chicas",
  "Honey Rock Landing",
  "Intecons Software",
  "landPKS",
  "Landscape Interactions",
  "LiteFarm - SPG project",
  "LiteFarm",
  "mdc-farmos2",
  "Million Acre Challenge",
  "MVP-Certifiers",
  "My Coffee Shop Group",
  "NACD Locally Led Conservation",
  "nexus",
  "NOFAMass ",
  "nx",
  "OMAFRA Topsoil",
  "OpenTEAM Equity",
  "OpenTEAM",
  "Our-Sci LLC",
  "Paicines Ranch",
  "Pasa",
  "Real Food Campaign (old)",
  "Reforestamos Mexico",
  "Regen Farmers Mutual",
  "Regen Future Capital",
  "Regen Network Development",
  "Regen1",
  "Rothamsted",
  "SHP",
  "Snapp Lab",
  "SOC Pilot",
  "Soil sensing and monitoring",
  "soilstack",
  "SRUC",
  "Stone Barns Center",
  "Stonyfield",
  "Svensk Kolinlagring",
  "Tech Matters",
  "TNPU",
  "Trial",
  "We Are For The Land",
];

export const ZONES = [
  "1a",
  "1b",
  "2a",
  "2b",
  "3a",
  "3b",
  "4a",
  "4b",
  "5a",
  "5b",
  "6a",
  "6b",
  "7a",
  "7b",
  "8a",
  "8b",
  "9a",
  "9b",
  "10a",
  "10b",
  "11a",
  "11b",
  "12a",
  "12b",
  "13a",
  "13b",
];
